name: example_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Dio
  dio: ^4.0.0
  #Rxdart
  rxdart: ^0.27.3
  #Provider
  provider: ^6.0.2
  #GetIt
  get_it: ^7.2.0
  #FlutterBloc
  flutter_bloc: ^8.0.1
  #Hive
  hive: ^2.0.5
  #Lottie
  lottie: ^1.2.1
  #Path Provider
  path_provider: ^2.0.8
  intl: ^0.17.0
  json_annotation: ^4.4.0
  dartz: ^0.10.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.0.4

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/